Set --disk_cache= for remote-cache using projects. (#285)
This unblocks Bazel downstream projects failing
due to:

    ERROR: Cannot enable HTTP-based and local disk
    cache simultaneously

Workaround for https://github.com/bazelbuild/bazel/issues/5382